### ISSUE TITLE
{$DECIMALS} not working to establish decimal places

### ISSUE THREAD

**Issue by egreising** [thhomas/dashboard-creator#37]
“Decimals:” in “VALUES” chart with an integer works well but with {$DECIMALS} it displays the value of DECIMALS instead of the OBS_VALUE with $DECIMALS decimal places. (see example https://dashboard-creator-thhomas-projects.vercel.app/chart/ExampleMULT4)

**Comment by thhomas** [comment]
Issue here is at the parser level, DECIMALS in this example is an attribute expressed at `dataSet` which is not handled by current version of sdmx-json-parser. 
cf. https://github.com/PacificCommunity/sdmx-json-parser/issues/5
